### ISSUE TITLE
restrict wiki

### ISSUE THREAD

**Issue by RRahmati95** [pvoosten/explicit-semantic-analysis#1]
I have a question about ESA implementation. I want to apply this method in My Master Thesis, but i want restrict its knowlege Database (Only papers about Design Patterns). You can help me?:((

**Comment by pvoosten** [comment]
If you format the text of the papers in wikipedia format, you can create your own wikipedia dump with it and use that as input for the indexer. However, limiting the concepts to articles about a single subject will probably not help you much.
