### ISSUE TITLE
Similarity of identical strings

### ISSUE THREAD

**Issue by interdonatos** [pvoosten/explicit-semantic-analysis#4]
Hi, 

I set everything up for both the english and french version of wikipedia, and everything works fine (in the sense that everything compiles and runs), but I made some tests and I think I am obtaining weird results, i.e., counter-intuitive values of similarity on several texts with both languages, and low similarity when comparing a string with itself...is that normal? (I guess no)

Thanks,
Roberto

**Comment by pvoosten** [comment]
Please share your code and how you set everything up.

**Comment by interdonatos** [comment]
Hi Philip , 

these are the only files I modified (nothing special, just some path and things like these), the rest is your original code. I am using the latest Wikipedia dump as you can see from the filename in the path.
When I run my ESATester on a String and itself (i.e, "Paris"), I get results lower than 1.0 (i.e., for Paris I get 0.02041097916662693).  Shouldn't it be 1.0 or I am missing something in the theory?


[tmp.zip](https://github.com/pvoosten/explicit-semantic-analysis/files/1499885/tmp.zip)

**Comment by pvoosten** [comment]
Can you create a gist or a diff that can be seen with a web browser instead?

**Comment by interdonatos** [comment]
Sorry, here's a gist:

https://gist.github.com/interdonatos/59889a8de7eaecf74cc338b7f8961160


I included just the french version (the error happens in both the english and french experiments, so that will be enough).

Thank you,
Roberto

**Comment by pvoosten** [comment]
Are you sure that the Lucene Analyzer you use during vectorization emits tokens? If not, that explains the very low scalar product.

**Comment by interdonatos** [comment]
I don't know... How can I check that? (anyway I am using the standard
analyzer in one case and the French one in the other, I have to config
something to make it work?)

Thanks,
Roberto

Il 24 nov 2017 13:57, "Philip van Oosten" <notifications@github.com> ha
scritto:

**Comment by pvoosten** [comment]
Please try out a simple Lucene indexing and search and dig into the Lucene documentation. That will help you understand Lucene. Then you can continue with more advanced stuff like ESA.

**Comment by interdonatos** [comment]
Thank you Philip, I'll do that. Just I don't understand if there's any reason the Lucene Analyzer shouldn't work using your original code on a standard wikipedia dump?

**Comment by pvoosten** [comment]
I understand your concern, but to address it, you must know the difference between indexing and search analyzers, see if indices are created correctly and know how to inspect the token stream from an analyzer. There is no point in not going through that first. Sorry.

**Comment by interdonatos** [comment]
Philip, I understand your reply and and I will go through it asap, and I thank you again for your help.
I have no concern :) But meanwhile I was asking if my first hypothesis was right, i.e., comparing a string (or a word) with itself, in your implementation, is supposed to output a SemanticSimilarity of 1.0 or not?
I am trying to perform a supersimple experiment with your original code, not to "tweak it" to do something special, but first I need to know if it works as I am supposing it should :) 

Thank you again,
Roberto

**Comment by pvoosten** [comment]
It should be 1.0, if I remember correctly, but only if the tokens emitted from the search analyzer match the tokens from the wikipedia analyzer exactly. If not, you could have a zero norm vector, which would result in no matching concepts whatsoever, which in turn would result in zero similarity.
I hope that explains the necessity to inspect tokens, indices and whatnot.
It is possible that a value between, but excluding 0 and 1 is forced, but I don’t remember exactly.

So yes, your 1.0 assumption is correct in theory, but there are a number of buts.

Btw, thanks for trying my implementation at all. Much appreciated.

**Comment by interdonatos** [comment]
Hi Philip, we have a solution :) 
And it's much more simpler than learning how Lucene really works...

You have an error in your SemanticSimilarityTool method: you should return the cosine similarity between the two concept vectors, not just the unnormalized dotProduct :) 
I did that and now works perfectly. I suggest you to correct your ConceptVector and SemanticSimilarityTool with something similar:

https://gist.github.com/interdonatos/32bb07097cbe29d6d3c9bd4077193e35

Cheers,
Roberto

**Comment by pvoosten** [comment]
Sorry, pal, but your solution is wrong. ConceptVector is a normalized vector, see the [ConceptVector constructor](https://github.com/pvoosten/explicit-semantic-analysis/blob/master/src/main/java/be/vanoosten/esa/tools/ConceptVector.java). The dot product of two normalized vectors is indeed the cosine similarity.

**Comment by pvoosten** [comment]
After a second look, there is indeed an error in the ConcepVector constructor, I think. The norm is calculated as the sum of squares, instead of the square root of that sum. I'll fix it in the browser.

Thank you for directing my attention to it.

**Comment by interdonatos** [comment]
Hi Philip, 
I was pretty sure that there's was something wrong with the implementation: I checked that the vectorizer is (hopefully) deterministic, and that for the same word it extracts the same concept vector. Than the cosine similarity between a vector and itself should be 1.0, while the code gave always very low values ;) 
At this point your fix and mine give equivalent results, but yours should be more efficient :)
